package com.example.data.model

data class MediaMetadata(
    val id: String,
    val title: String,
    val webpageUrl: String,
    val uploader: String = "",
    val channel: String = "",
    val durationSeconds: Long = 0,
    val viewCount: Long? = null,
    val likeCount: Long? = null,
    val uploadDate: String = "",
    val description: String = "",
    val thumbnail: String = "",
    val isPlaylist: Boolean = false,
    val playlistCount: Int = 0,
    val playlistEntries: List<PlaylistEntry> = emptyList(),
    val formats: List<FormatInfo> = emptyList(),
    val subtitles: List<SubtitleTrack> = emptyList(),
    val extractorName: String = "generic",
    val directDownloadUrl: String? = null
) {
    val durationFormatted: String
        get() {
            if (durationSeconds <= 0) return "--:--"
            val hours = durationSeconds / 3600
            val minutes = (durationSeconds % 3600) / 60
            val seconds = durationSeconds % 60
            return if (hours > 0) {
                String.format("%d:%02d:%02d", hours, minutes, seconds)
            } else {
                String.format("%d:%02d", minutes, seconds)
            }
        }
}

data class FormatInfo(
    val formatId: String,
    val ext: String = "mp4",
    val resolution: String = "",
    val width: Int? = null,
    val height: Int? = null,
    val fps: Double? = null,
    val vcodec: String = "none",
    val acodec: String = "none",
    val tbr: Double? = null,
    val vbr: Double? = null,
    val abr: Double? = null,
    val filesize: Long? = null,
    val filesizeApprox: Long? = null,
    val formatNote: String = "",
    val url: String = "",
    val protocol: String = "https",
    val isVideoOnly: Boolean = (vcodec != "none" && vcodec.isNotBlank()) && (acodec == "none" || acodec.isBlank()),
    val isAudioOnly: Boolean = (acodec != "none" && acodec.isNotBlank()) && (vcodec == "none" || vcodec.isBlank()),
    val isMuxed: Boolean = (vcodec != "none" && vcodec.isNotBlank()) && (acodec != "none" && acodec.isNotBlank())
) {
    val displayResolution: String
        get() = when {
            height != null && height > 0 -> "${height}p"
            resolution.isNotBlank() && resolution != "audio only" -> resolution
            isAudioOnly -> "Audio Only"
            else -> "Default"
        }

    val displayFileSize: String
        get() {
            val bytes = filesize ?: filesizeApprox
            return if (bytes != null && bytes > 0) {
                formatBytes(bytes)
            } else {
                "Unknown size"
            }
        }

    val codecSummary: String
        get() = when {
            isAudioOnly -> "Audio: ${acodec.uppercase()}"
            isVideoOnly -> "Video: ${vcodec.uppercase()} (No Audio)"
            isMuxed -> "${vcodec.uppercase()} + ${acodec.uppercase()}"
            else -> ext.uppercase()
        }
}

data class SubtitleTrack(
    val language: String,
    val name: String,
    val ext: String = "vtt",
    val url: String = "",
    val isAutoGenerated: Boolean = false
)

data class PlaylistEntry(
    val id: String,
    val title: String,
    val url: String,
    val durationSeconds: Long = 0,
    val thumbnail: String = "",
    val uploader: String = "",
    var isSelected: Boolean = true
) {
    val durationFormatted: String
        get() {
            if (durationSeconds <= 0) return ""
            val hours = durationSeconds / 3600
            val minutes = (durationSeconds % 3600) / 60
            val seconds = durationSeconds % 60
            return if (hours > 0) {
                String.format("%d:%02d:%02d", hours, minutes, seconds)
            } else {
                String.format("%d:%02d", minutes, seconds)
            }
        }
}

fun formatBytes(bytes: Long): String {
    if (bytes < 1024) return "$bytes B"
    val exp = (Math.log(bytes.toDouble()) / Math.log(1024.0)).toInt()
    val pre = "KMGTPE"[exp - 1]
    return String.format("%.2f %sB", bytes / Math.pow(1024.0, exp.toDouble()), pre)
}

fun formatSpeed(bytesPerSec: Double): String {
    if (bytesPerSec <= 0) return "0 B/s"
    val exp = (Math.log(bytesPerSec) / Math.log(1024.0)).toInt().coerceIn(0, 4)
    val pre = if (exp > 0) "KMGTPE"[exp - 1].toString() else ""
    return String.format("%.2f %sB/s", bytesPerSec / Math.pow(1024.0, exp.toDouble()), pre)
}

fun formatEta(etaSeconds: Long): String {
    if (etaSeconds <= 0) return "--"
    val hours = etaSeconds / 3600
    val minutes = (etaSeconds % 3600) / 60
    val seconds = etaSeconds % 60
    return if (hours > 0) {
        String.format("%dh %02dm", hours, minutes)
    } else if (minutes > 0) {
        String.format("%dm %02ds", minutes, seconds)
    } else {
        String.format("%ds", seconds)
    }
}
