package com.example.extraction

import com.example.core.model.CanonicalMediaResult
import com.example.core.model.CanonicalMetadata
import com.example.core.model.MediaFormat
import com.example.core.model.MediaSize
import com.example.core.model.SizeProvenance
import com.example.data.model.PlaylistEntry
import com.example.data.model.SubtitleTrack
import com.example.extraction.model.YtDlpFormatDto
import com.example.extraction.model.YtDlpInfoDto

object MetadataNormalizer {

    fun resolveMediaSize(filesize: Long?, filesizeApprox: Long?, httpContentLength: Long? = null): MediaSize {
        return when {
            filesize != null && filesize > 0 -> MediaSize.Exact(filesize, SizeProvenance.FORMAT_FILESIZE)
            filesizeApprox != null && filesizeApprox > 0 -> MediaSize.Approximate(filesizeApprox, SizeProvenance.FORMAT_FILESIZE_APPROX)
            httpContentLength != null && httpContentLength > 0 -> MediaSize.HttpContentLength(httpContentLength, SizeProvenance.VERIFIED_HTTP)
            else -> MediaSize.Unknown("Size not provided by source")
        }
    }

    fun normalizeFormat(dto: YtDlpFormatDto, httpContentLength: Long? = null): MediaFormat {
        val size = resolveMediaSize(dto.filesize, dto.filesizeApprox, httpContentLength)
        val height = dto.height
        val resolution = dto.resolution ?: (if (height != null && height > 0) "${height}p" else "")

        return MediaFormat(
            formatId = dto.formatId,
            ext = dto.ext,
            resolution = resolution,
            width = dto.width,
            height = dto.height,
            fps = dto.fps,
            vcodec = dto.vcodec ?: "none",
            acodec = dto.acodec ?: "none",
            tbr = dto.tbr,
            vbr = dto.vbr,
            abr = dto.abr,
            size = size,
            formatNote = dto.formatNote ?: "",
            url = dto.url,
            protocol = dto.protocol ?: "https"
        )
    }

    fun normalizeYtDlpInfo(
        dto: YtDlpInfoDto,
        sourceUrl: String,
        canonicalUrl: String,
        platform: String = "generic"
    ): CanonicalMediaResult {
        val normalizedFormats = dto.formats.map { normalizeFormat(it) }

        val hasValidPlaylistEntries = dto.isPlaylist && dto.entries.isNotEmpty()
        val playlistEntries = if (hasValidPlaylistEntries) {
            dto.entries.map {
                PlaylistEntry(
                    id = it.id,
                    title = it.title,
                    url = it.url,
                    durationSeconds = it.duration,
                    thumbnail = it.thumbnail,
                    uploader = it.uploader
                )
            }
        } else emptyList()

        val subtitles = dto.subtitles.map {
            SubtitleTrack(
                language = it.language,
                name = it.name ?: it.language.uppercase(),
                ext = it.ext,
                url = it.url,
                isAutoGenerated = false
            )
        }

        val canonicalMetadata = CanonicalMetadata(
            title = dto.title,
            uploader = dto.uploader,
            channel = dto.channel,
            durationSeconds = dto.duration,
            viewCount = dto.viewCount,
            likeCount = dto.likeCount,
            uploadDate = dto.uploadDate,
            description = dto.description,
            thumbnail = dto.thumbnail,
            isPlaylist = hasValidPlaylistEntries,
            playlistCount = if (hasValidPlaylistEntries) playlistEntries.size else 0,
            playlistEntries = playlistEntries,
            subtitles = subtitles,
            extractorName = dto.extractor ?: "yt-dlp"
        )

        return CanonicalMediaResult(
            sourceUrl = sourceUrl,
            canonicalUrl = canonicalUrl,
            platform = platform,
            intent = if (hasValidPlaylistEntries) "playlist" else "video",
            metadata = canonicalMetadata,
            formats = normalizedFormats
        )
    }
}
