package com.example.extraction

import android.content.Context
import com.example.data.model.AppSettings
import com.example.engine.YtDlpBinaryManager
import com.example.engine.YtDlpProcessRunner
import com.example.routing.RoutingDecision
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class YtDlpStrategy(private val context: Context? = null) : ExtractionStrategy {

    override val name: String = "YTDLP"

    override suspend fun canHandle(url: String, decision: RoutingDecision): Boolean {
        return decision.allowYtDlp
    }

    override suspend fun extract(
        url: String,
        decision: RoutingDecision,
        settings: AppSettings?
    ): ExtractionEvidence = withContext(Dispatchers.IO) {
        if (!decision.allowYtDlp) {
            return@withContext ExtractionEvidence()
        }

        try {
            if (context != null) {
                YtDlpBinaryManager.ensureInitialized(context)
            }

            val cliResult = YtDlpProcessRunner.extractInfoDto(
                binaryPath = "",
                url = url,
                cookiesPath = settings?.cookiesFilePath?.ifBlank { null },
                customArgs = settings?.customYtDlpArgs ?: ""
            )

            if (cliResult.isSuccess) {
                val infoDto = cliResult.getOrThrow()
                val candidates = CandidateNormalizer.fromYtDlpInfo(infoDto, url, decision.intent)
                val canonicalMeta = com.example.core.model.CanonicalMetadata(
                    title = infoDto.title,
                    uploader = infoDto.uploader,
                    channel = infoDto.channel,
                    durationSeconds = infoDto.duration,
                    viewCount = infoDto.viewCount,
                    likeCount = infoDto.likeCount,
                    uploadDate = infoDto.uploadDate,
                    description = infoDto.description,
                    thumbnail = infoDto.thumbnail,
                    isPlaylist = infoDto.isPlaylist,
                    playlistCount = if (infoDto.isPlaylist) infoDto.entries.size else 0,
                    playlistEntries = infoDto.entries.map { e ->
                        com.example.data.model.PlaylistEntry(
                            id = e.id,
                            title = e.title,
                            url = e.url,
                            durationSeconds = e.duration,
                            thumbnail = e.thumbnail,
                            uploader = e.uploader
                        )
                    },
                    subtitles = infoDto.subtitles.map { s ->
                        com.example.data.model.SubtitleTrack(
                            language = s.language,
                            name = s.name ?: s.language.uppercase(),
                            ext = s.ext,
                            url = s.url,
                            isAutoGenerated = false
                        )
                    },
                    extractorName = infoDto.extractor ?: (if (infoDto.isPlaylist) "yt-dlp:playlist" else "yt-dlp"),
                    directDownloadUrl = null,
                    filesize = infoDto.filesize,
                    filesizeApprox = infoDto.filesizeApprox,
                    overallSize = MetadataNormalizer.resolveMediaSize(infoDto.filesize, infoDto.filesizeApprox)
                )
                ExtractionEvidence(candidates = candidates, metadata = canonicalMeta)

            } else {
                val err = cliResult.exceptionOrNull()?.message ?: "yt-dlp extraction failed"
                ExtractionEvidence(
                    warnings = listOf("yt-dlp extraction failed: $err"),
                    failedStrategies = listOf(name)
                )
            }
        } catch (e: Exception) {
            ExtractionEvidence(
                warnings = listOf("yt-dlp extraction exception: ${e.message}"),
                failedStrategies = listOf(name)
            )
        }
    }
}
