package com.example.extraction

import com.example.data.model.FormatInfo
import com.example.data.model.MediaMetadata
import com.example.data.model.PlaylistEntry
import com.example.data.model.SubtitleTrack
import com.example.extraction.model.YtDlpFormatDto
import com.example.extraction.model.YtDlpInfoDto

object YtDlpMetadataMapper {

    fun mapToMediaMetadata(dto: YtDlpInfoDto, originalUrl: String): MediaMetadata {
        val formats = dto.formats.map { mapFormat(it) }
        val subtitles = dto.subtitles.map {
            SubtitleTrack(
                language = it.language,
                name = it.name ?: it.language.uppercase(),
                ext = it.ext,
                url = it.url,
                isAutoGenerated = false
            )
        }

        val hasValidPlaylistEntries = dto.isPlaylist && dto.entries.isNotEmpty()
        val playlistEntries = if (hasValidPlaylistEntries) {
            dto.entries.map {
                PlaylistEntry(
                    id = it.id,
                    title = it.title,
                    url = it.url,
                    durationSeconds = it.duration,
                    thumbnail = it.thumbnail,
                    uploader = it.uploader
                )
            }
        } else {
            emptyList()
        }

        return MediaMetadata(
            id = dto.id,
            title = dto.title,
            webpageUrl = dto.webpageUrl ?: originalUrl,
            uploader = dto.uploader,
            channel = dto.channel,
            durationSeconds = dto.duration,
            viewCount = dto.viewCount,
            likeCount = dto.likeCount,
            uploadDate = dto.uploadDate,
            description = dto.description,
            thumbnail = dto.thumbnail,
            isPlaylist = hasValidPlaylistEntries,
            playlistCount = if (hasValidPlaylistEntries) playlistEntries.size else 0,
            playlistEntries = playlistEntries,
            formats = formats,
            subtitles = subtitles,
            extractorName = dto.extractor ?: if (hasValidPlaylistEntries) "yt-dlp:playlist" else "yt-dlp"
        )
    }

    fun mapFormat(dto: YtDlpFormatDto): FormatInfo {
        return FormatInfo(
            formatId = dto.formatId,
            ext = dto.ext,
            resolution = dto.resolution ?: (if (dto.height != null && dto.height > 0) "${dto.height}p" else ""),
            width = dto.width,
            height = dto.height,
            fps = dto.fps,
            vcodec = dto.vcodec ?: "none",
            acodec = dto.acodec ?: "none",
            tbr = dto.tbr,
            vbr = dto.vbr,
            abr = dto.abr,
            filesize = dto.filesize,
            filesizeApprox = dto.filesizeApprox,
            formatNote = dto.formatNote ?: "",
            url = dto.url,
            protocol = dto.protocol ?: "https"
        )
    }
}
