export enum DownloadStatus {
  QUEUED = 'Queued',
  ANALYZING = 'Analyzing',
  DOWNLOADING = 'Downloading',
  PAUSED = 'Paused',
  PROCESSING = 'Processing',
  COMPLETED = 'Completed',
  FAILED = 'Failed',
  CANCELLED = 'Cancelled',
}

export enum MediaType {
  VIDEO = 'Video',
  AUDIO = 'Audio',
  PLAYLIST = 'Playlist',
}

export enum OutputContainer {
  AUTO = 'auto',
  MP4 = 'mp4',
  MKV = 'mkv',
  WEBM = 'webm',
}

export enum AudioFormat {
  BEST = 'best',
  MP3 = 'mp3',
  M4A = 'm4a',
  OPUS = 'opus',
  WAV = 'wav',
  FLAC = 'flac',
}

export const AudioFormatDisplay: Record<AudioFormat, string> = {
  [AudioFormat.BEST]: 'Best Quality',
  [AudioFormat.MP3]: 'MP3 (.mp3)',
  [AudioFormat.M4A]: 'M4A / AAC (.m4a)',
  [AudioFormat.OPUS]: 'Opus (.opus)',
  [AudioFormat.WAV]: 'WAV Lossless (.wav)',
  [AudioFormat.FLAC]: 'FLAC Lossless (.flac)',
};

export enum VideoQualityPreset {
  BEST = 'Best Available',
  RES_4K = '4K (2160p)',
  RES_1440P = '2K (1440p)',
  RES_1080P = 'Full HD (1080p)',
  RES_720P = 'HD (720p)',
  RES_480P = 'SD (480p)',
  RES_360P = 'Low (360p)',
  CUSTOM = 'Custom Format',
}

export enum AudioQualityPreset {
  BEST = 'Best Original',
  KBPS_320 = '320 kbps (Ultra)',
  KBPS_256 = '256 kbps (High)',
  KBPS_192 = '192 kbps (Medium)',
  KBPS_128 = '128 kbps (Standard)',
  CUSTOM = 'Custom Bitrate',
}

export enum LogLevel {
  DEBUG = 'DEBUG',
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
}

export enum EngineState {
  MISSING = 'Missing',
  INSTALLING = 'Installing',
  READY = 'Ready',
  INVALID = 'Invalid / Not Executable',
  UPDATING = 'Updating',
  ERROR = 'Error',
}

export enum HistorySortOrder {
  NEWEST = 'Newest First',
  OLDEST = 'Oldest First',
  SIZE_DESC = 'Largest File',
  NAME_ASC = 'Name (A-Z)',
}

export enum NavigationTab {
  HOME = 'HOME',
  DOWNLOADS = 'DOWNLOADS',
  HISTORY = 'HISTORY',
  SETTINGS = 'SETTINGS',
}

export interface FormatInfo {
  formatId: string;
  ext: string;
  resolution: string;
  width?: number | null;
  height?: number | null;
  fps?: number | null;
  vcodec: string;
  acodec: string;
  tbr?: number | null;
  vbr?: number | null;
  abr?: number | null;
  filesize?: number | null;
  filesizeApprox?: number | null;
  formatNote: string;
  url: string;
  protocol: string;
  isVideoOnly: boolean;
  isAudioOnly: boolean;
  isMuxed: boolean;
}

export interface SubtitleTrack {
  language: string;
  name: string;
  ext: string;
  url: string;
  isAutoGenerated: boolean;
}

export interface PlaylistEntry {
  id: string;
  title: string;
  url: string;
  durationSeconds: number;
  thumbnail: string;
  uploader: string;
  isSelected: boolean;
}

export interface MediaMetadata {
  id: string;
  title: string;
  webpageUrl: string;
  uploader: string;
  channel: string;
  durationSeconds: number;
  viewCount?: number | null;
  likeCount?: number | null;
  uploadDate: string;
  description: string;
  thumbnail: string;
  isPlaylist: boolean;
  playlistCount: number;
  playlistEntries: PlaylistEntry[];
  formats: FormatInfo[];
  subtitles: SubtitleTrack[];
  extractorName: string;
  directDownloadUrl?: string | null;
}

export interface DownloadTask {
  id: string;
  url: string;
  title: string;
  thumbnail: string;
  status: DownloadStatus;
  progress: number; // 0.0 to 100.0
  downloadedBytes: number;
  totalBytes: number;
  speedBytesPerSec: number;
  etaSeconds: number;
  formatId: string;
  formatDescription: string;
  mediaType: MediaType;
  outputPath: string;
  mediaUrl?: string; // Direct stream/blob URL for playback
  errorMessage?: string | null;
  detailedLogs: string;
  createdTimestamp: number;
  completedTimestamp?: number | null;
  isPlaylist: boolean;
  playlistIndex: number;
  playlistTotal: number;
  audioBitrate?: number | null;
  targetContainer: string;
  embedSubs: boolean;
  embedThumbnail: boolean;
  subtitleLangs: string;
}

export interface DownloadHistoryItem {
  id: string;
  title: string;
  url: string;
  thumbnail: string;
  filePath: string;
  fileSize: number;
  mediaType: MediaType;
  formatDescription: string;
  completedTimestamp: number;
  uploader: string;
  durationSeconds: number;
  mediaUrl?: string;
}

export interface LogEntry {
  logId: number;
  taskId?: string | null;
  level: LogLevel;
  tag: string;
  message: string;
  timestamp: number;
}

export interface AppSettings {
  maxConcurrentDownloads: number;
  defaultVideoQuality: VideoQualityPreset;
  defaultAudioQuality: AudioQualityPreset;
  defaultContainer: OutputContainer;
  defaultAudioFormat: AudioFormat;
  downloadLocationUri: string;
  downloadLocationDisplayName: string;
  resumeDownloads: boolean;
  retryCount: number;
  customYtDlpArgs: string;
  verboseLogging: boolean;
  cookiesFilePath: string;
  sanitizeFilenames: boolean;
  organizeByUploader: boolean;
  embedSubtitles: boolean;
  embedThumbnail: boolean;
  filenameTemplate: string;
  autoStartDownloads: boolean;
  confirmDelete: boolean;
  darkTheme: boolean;
}

export interface EngineDiagnosticError {
  title: string;
  reason: string;
  suggestedAction: string;
  technicalDetails: string;
}

export interface YtDlpStatus {
  isReady: boolean;
  version: string;
  state: EngineState;
}

export interface FFmpegStatus {
  isAvailable: boolean;
  version: string;
  ffprobeVersion?: string;
  state: EngineState;
}
